### ISSUE TITLE
Overhaul Google Cloud Function component

### ISSUE THREAD

**Issue by pmuens** [serverless/components#258]
## Google Cloud Function component analysis

In https://github.com/serverless/components/pull/253 we've updated the GCF component so that it can be used to (re)`deploy` and `remove` Google Cloud Functions. While working on this we've found other issues / design flaws we need to tackle. Here's a quick writeup which describes improvements, problems and questions we've uncovered during this codebase analysis.

---

### Implementation against new type system:
- Add `index.js` file
- Add `serverless.yml` file
- Add `package.json` file
    - `npm install archiver` package
- Add `README.md` file
    - Write documentation about inner-workings
    - Add reference to component in root `README.md` file
- Implement `getSinkConfig` function
- Implement `pack` function
    - Take care of proper shim handling
- Implement `deploy` function
    - Implement `create` functionality
        - Implement bucket creation logic
    - Implement `update` functionality
        - Implement bucket cleanup logic
- Implement `remove` function
    - Implement `remove` functionality
        - Implement "full" bucket cleanup logic
- Write tests
    - `index.test.js`
    - ... (for all other files)

---

### Todos (check after following implementation above):
- [ ] Make it possible to switch from `httpsTrigger` to `eventTrigger` and vice versa
- [x] Make sure that component inputs support „all“ possible configurations (according to GCF docs)
    - [x] `availableMemoryMb`
    - [x] `entryPoint`
    - [x] `description`
    - [x] `environmentVariables`
    - [x] `eventTrigger`
    - [x] `httpsTrigger`
    - [x] `labels`
    - [x] `maxInstances`
    - [x] `name`
    - [x] `network`
    - [x] `runtime`
    - [ ] `sourceArchiveUrl`
    - [ ] `sourceRepository`
    - [x] `sourceUploadUrl`
    - [x] `timeout`
- [ ] Revisit components outputs and figure out which ones make sense (remove others)
- [x] Await function creation (this might slow down function creation)
- [x] Replace `keyfile` from inputs with `clientEmail` and `privateKey`
- [x] Restructure / further refactor codebase to make it even easier to (unit) test

### Questions:
- Is it possible for a Google Cloud Function to switch from a `httpsTrigger` to an `eventTrigger` without re-deploying it?
- Should we wait for the response of function creations / removals?
- Should we use the [storage bucket component](https://github.com/serverless/components/issues/264) programatically behind the scenes or use our own, specialized implementation within our Google Cloud Function component?

### Problems / Limitations:
- One can only create a new bucket every 2 seconds (see: https://cloud.google.com/storage/quotas) how do we deal with that if we have a project which has many GCF where we create one bucket per function?
